# Generated by Django 4.1 on 2022-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0003_alter_character_height_alter_character_mass"),
        ("planets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("episode", models.CharField(max_length=20)),
                ("opening_text", models.TextField()),
                ("director", models.CharField(max_length=100)),
                ("producer", models.CharField(max_length=100)),
                ("release_date", models.CharField(max_length=20)),
                (
                    "characters",
                    models.ManyToManyField(blank=True, to="characters.character"),
                ),
                ("planets", models.ManyToManyField(blank=True, to="planets.planet")),
            ],
        ),
    ]
