# Generated by Django 4.1 on 2022-11-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_alter_character_height_alter_character_mass"),
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="characters",
            field=models.ManyToManyField(
                blank=True, related_name="film_character_set", to="characters.character"
            ),
        ),
    ]
