# Generated by Django 4.1 on 2022-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_character_birth_year_character_eye_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="height",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="character",
            name="mass",
            field=models.CharField(max_length=20),
        ),
    ]
