# Generated by Django 4.1 on 2022-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("diameter", models.CharField(max_length=20)),
                ("climate", models.CharField(max_length=20)),
                ("gravity", models.CharField(max_length=20)),
                ("terrain", models.CharField(max_length=20)),
                ("population", models.CharField(max_length=20)),
            ],
        ),
    ]
