# Generated by Django 3.2.16 on 2022-12-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planet',
            name='diameter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planet',
            name='gravity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(max_length=100),
        ),
    ]
